# Generated by Django 3.0.14 on 2023-01-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnA', '0012_followquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='file',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
