# Generated by Django 3.0.14 on 2023-01-03 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qnA', '0013_question_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='file',
        ),
    ]
