# Generated by Django 3.0.14 on 2023-02-25 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qnA', '0014_remove_question_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={},
        ),
    ]
